export const vietnamLocations = {
  'Hà Nội': ['Hoàn Kiếm', 'Ba Đình', 'Hai Bà Trưng', 'Dong Da', 'Tây Hồ', 'Cầu Giấy', 'Thanh Xuân', 'Hoàng Mai', 'Long Biên', 'Bắc Từ Liêm', 'Nam Từ Liêm'],
  'Thành phố Hồ Chí Minh': ['Quận 1', 'Quận 2', 'Quận 3', 'Quận 4', 'Quận 5', 'Quận 6', 'Quận 7', 'Quận 8', 'Quận 9', 'Quận 10', 'Quận 11', 'Quận 12', 'Bình Thạnh', 'Gò Vấp', 'Phú Nhuận', 'Tân Bình', 'Tân Phú', 'Thủ Đức'],
  'Đà Nẵng': ['Hải Châu', 'Thanh Khê', 'Sơn Trà', 'Ngũ Hành Sơn', 'Liên Chiểu', 'Cẩm Lệ'],
  'Hải Phòng': ['Hồng Bàng', 'Ngô Quyền', 'Lê Chân', 'Kiến An', 'Hải An', 'Bạch Long Vĩ'],
  'Cần Thơ': ['Ninh Kiều', 'Bình Thủy', 'Cái Răng', 'O Môn', 'Thốt Nốt'],
  'Thừa Thiên Huế': ['Thành phố Huế', 'Phú Vang', 'A Lưới', 'Phong Điền', 'Quảng Điền'],
  'Đồng Nai': ['Biên Hòa', 'Trảng Bom', 'Vĩnh Cửu', 'Thống Nhất', 'Long Thành', 'Xuân Lộc'],
  'Bình Dương': ['Thành phố Dĩ An', 'Thị xã Thuận An', 'Thị xã Tân Uyên', 'Bến Cát', 'Phú Giáo', 'Bàu Bàng'],
  'Bình Phước': ['Đồng Xoài', 'Phước Long', 'Bình Long', 'Chơn Thành', 'Bù Dăng'],
  'Tây Ninh': ['Tây Ninh', 'Trảng Bàng', 'Dương Minh Châu', 'Tân Biên', 'Tân Châu'],
  'Long An': ['Tân An', 'Cần Đước', 'Cần Giuộc', 'Mỹ Xuyên', 'Thạnh Hóa', 'Bến Lức'],
  'Tiền Giang': ['Mỹ Tho', 'Gò Công', 'Gò Công Đông', 'Gò Công Tây', 'Cái Bè', 'Cù Lao Dung'],
  'Vĩnh Long': ['Vĩnh Long', 'Mộtay', 'Trà Ôn', 'Bình Minh', 'Tam Bình', 'Long Hồ'],
  'An Giang': ['Long Xuyên', 'Châu Đốc', 'Tân Châu', 'Phú Tân', 'Chợ Mới', 'An Phú'],
  'Kiên Giang': ['Rạch Giá', 'Hà Tiên', 'Phú Quốc', 'Kiên Lương', 'Gò Quao', 'An Minh'],
  'Cà Mau': ['Cà Mau', 'Thới Bình', 'Trần Văn Thời', 'Cái Nước', 'Năm Căn', 'U Minh'],
  'Quảng Ninh': ['Hạ Long', 'Móng Cái', 'Cẩm Phả', 'Uông Bí', 'Bình Liêu', 'Tiên Yên'],
  'Hải Dương': ['Hải Dương', 'Chí Linh', 'Kinh Môn', 'Nam Sách', 'Ninh Giang'],
  'Hưng Yên': ['Hưng Yên', 'Mỹ Hào', 'Ân Thi', 'Tiên Lữ', 'Yên Mỹ'],
  'Hà Nam': ['Phủ Lý', 'Duy Tiên', 'Kim Bảng', 'Thanh Liêm', 'Bình Lục'],
  'Nam Định': ['Nam Định', 'Thành Phố', 'Giao Thủy', 'Ý Yên', 'Hải Hậu'],
  'Ninh Bình': ['Ninh Bình', 'Tam Điệp', 'Hoa Lư', 'Nho Quan', 'Yên Khánh'],
  'Thanh Hóa': ['Thanh Hóa', 'Sầm Sơn', 'Mường Lát', 'Bá Thước', 'Quan Sơn'],
  'Nghệ An': ['Vinh', 'Cửa Lò', 'Anh Sơn', 'Diễn Châu', 'Quỳnh Lưu'],
  'Hà Tĩnh': ['Hà Tĩnh', 'Hồng Lĩnh', 'Thạch Hà', 'Can Lộc', 'Kỳ Anh'],
  'Quảng Bình': ['Đông Hà', 'Quảng Trị', 'Vĩnh Linh', 'Đakrông'],
  'Quảng Trị': ['Quảng Trị', 'Cồn Cỏ', 'Vĩnh Linh'],
  'Quảng Nam': ['Hội An', 'Tam Kỳ', 'Duy Xuyên', 'Thăng Bình', 'Nông Sơn'],
  'Quảng Ngãi': ['Quảng Ngãi', 'Tư Nghĩa', 'Lý Sơn', 'Minh Long'],
  'Bình Định': ['Quy Nhơn', 'Hoài Ân', 'An Lão', 'Tây Sơn'],
  'Phú Yên': ['Tuy Hòa', 'Đông Hòa', 'Sông Cầu', 'Tuy An'],
  'Khánh Hòa': ['Nha Trang', 'Cam Ranh', 'Cam Lâm', 'Ninh Hòa', 'Vạn Ninh'],
  'Ninh Thuận': ['Phan Rang-Tháp Chàm', 'Ninh Hải', 'Thuận Bắc', 'Thuận Nam'],
  'Bình Thuận': ['Phan Thiết', 'La Gi', 'Tuy Phong', 'Hàm Tân', 'Hàm Thuận Bắc'],
  'Lâm Đồng': ['Đà Lạt', 'Đức Trọng', 'Lâm Hà', 'Di Linh', 'Bảo Lộc'],
  'Đắk Lắk': ['Buôn Ma Thuột', 'Buôn Hồ', 'Cư M\'gar', 'Krông Bông'],
  'Đắk Nông': ['Gia Nghĩa', 'Đắk Mil', 'Đắk R Lấp'],
  'Yên Bái': ['Yên Bái', 'Lục Yên', 'Văn Yên', 'Mù Căng Chải'],
  'Tuyên Quang': ['Tuyên Quang', 'Na Hang', 'Chiêm Hóa', 'Nơn'],
  'Lào Cai': ['Lào Cai', 'Sa Pa', 'Bắc Hà', 'Bảo Thắng'],
  'Cao Bằng': ['Cao Bằng', 'Bảo Lạc', 'Thạch An', 'Hà Quảng'],
  'Bắc Kạn': ['Bắc Kạn', 'Ngân Sơn', 'Ba Bể'],
  'Thái Nguyên': ['Thái Nguyên', 'Sơn Dương', 'Định Hóa', 'Phổ Yên'],
  'Lạng Sơn': ['Lạng Sơn', 'Chi Lăng', 'Văn Lăng', 'Cao Lộc'],
  'Quảng Ninh (tiếp)': ['Đông Triều', 'Vân Đồn', 'Yên Hưng'],
  'Bắc Giang': ['Bắc Giang', 'Yên Thế', 'Lâm Thao', 'Hiệp Hòa'],
  'Bắc Ninh': ['Bắc Ninh', 'Từ Sơn', 'Yên Phong', 'Gia Bình'],
  'Hà Giang': ['Hà Giang', 'Đồng Văn', 'Mèo Vạc', 'Yên Minh'],
  'Sơn La': ['Sơn La', 'Mộc Châu', 'Phù Yên', 'Yên Châu'],
  'Điện Biên': ['Điện Biên Phủ', 'Mường Ảng', 'Nậm Pồ'],
  'Lai Châu': ['Lai Châu', 'Tam Đường', 'Sìn Hồ', 'Phong Thổ'],
}

export const getDistrictsByProvince = (province: string): string[] => {
  return vietnamLocations[province as keyof typeof vietnamLocations] || []
}
